name: Deploy

env:
  CI: false

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    tags:
      - prod/*

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  serverless:
    # Name the Job
    name: Upload Extensions
    # Set the type of machine to run on
    runs-on: ubuntu-20.04

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install node modules
        run: yarn install
      - name: Build ${{ env.GITHUB_REF_SLUG }}
        run: yarn build:prod
      - name: Publish ${{ env.GITHUB_REF_SLUG }}
        run: yarn serverless:deploy:prod
      - name: Build extensions ${{ env.GITHUB_REF_SLUG }} stack
        run: yarn build:extension
      - name: Upload bundle into S3
        run: yarn upload:bundle:prod
        env: # Or as an environment variable
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
